argocd:
  openshift:
    enabled: true

dependencies:
  cnpg:
    containerSecurityContextNull: true
  istio:
    base:
      deploy: false
    ingressgateway:
      containerSecurityContextNull: true
      service:
        type: ClusterIP
    istiod:
      deploy: false
  kiali:
    deploy: false
  opentelemetryOperator:
    securityContextNull: true
  ome:
    openshift:
      enabled: true
  purplePill:
    openshift:
      enabled: true
  prometheus:
    deploy: false
    deployScrapeconfigsCRDOnly: true
  tekton:
    openshift:
      enabled: true

dns:
  openshift:
    routes: true

monitoring:
  otel:
    openshift:
      enabled: true
  prometheus:
    host: "prometheus-k8s.openshift-monitoring.svc.cluster.local"
    port: 9091
    tls:
      ca:
        configMap:
          name: "ocp-service-ca"
          openshiftServiceCa: true
        custom: true
      enabled: true
    tokenAuth: true

routing:
  openshift:
    routes: true  # Only `passthrough` Routes creation is supported by this chart.
                  # For `reencrypt`, set this to `false` and
                  # install Routes manually using stanadlone `openshift-tls-reencrypt` chart.
  istio:
    ingress:
      gateway:
        catchAll: true